### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [innative-sdk/innative#13]
I would like to point out that identifiers like “[`__INNATIVE_H__IN__`](https://github.com/innative-sdk/innative/blob/69ad7053f97ffd81a75de074c63b678448d9c0cf/include/innative/innative.h#L17 "Update candidate")” and “[`__WASM_INSTRUCTION`](https://github.com/innative-sdk/innative/blob/5a4d75ec965b1a13390a1d365ea9cc8915a38af7/include/innative/schema.h#L146 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by blackhole12** [comment]
All identifiers were switch to compliant ones in 60da02e

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/innative-sdk/innative/commit/60da02e20a2205747fbc518ed2e16579b56c9053 "Renaming of identifiers").

Do you [care for naming conventions also from the C++ programming language](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by blackhole12** [comment]
This project is not using the standard C++ naming convention.

**Comment by elfring** [comment]
Will components from this software ever be compiled by C++ development tools?
