### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by jedisct1** [innative-sdk/innative#15]
Hi,

Looks like the precompiled Linux binaries are not portable.

Trying to run either `innative-cmd` or `innative-test` crashes on my machine:

```text
Program received signal SIGILL, Illegal instruction.
```

This happens in `llvm::WebAssemblyTargetWasmStreamer::emitEndFunc()`:

```text
   0x00007ffff54c1e45 <+121>:	lea    0x1e8af11(%rip),%rax        # 0x7ffff734cd5d
   0x00007ffff54c1e4c <+128>:	lea    0x1e8af59(%rip),%rcx        # 0x7ffff734cdac
=> 0x00007ffff54c1e53 <+135>:	vinserti128 $0x1,%xmm0,%ymm5,%ymm5
   0x00007ffff54c1e59 <+141>:	vpinsrq $0x1,%rax,%xmm4,%xmm0
   0x00007ffff54c1e5f <+147>:	vmovq  %rdx,%xmm4
```

Sure, my CPU is a Sandy Bridge, it has the AVX, but not AVX2 instruction set.

So, it looks like LLVM was compiled with `-march=native` on your computer. Which doesn't work well for people with older CPUs.

**Comment by blackhole12** [comment]
Whoops, that definitely should not have happened. `--march=native` should have been removed from the compiled binaries, but it snuck back in at some point.

**Comment by blackhole12** [comment]
@jedisct1 I was unable to find any flags in the LLVM compilation that would have created those instructions, so I instead just recompiled inNative without `--march=native` and [reuploaded the files](https://github.com/innative-sdk/innative/releases/tag/v0.1.0). Can you try the files and see if they work?

**Comment by jedisct1** [comment]
Same :(

The AVX2 opcodes are in LLVM (statically linked in `libinnative.so`), not in inNative.

**Comment by blackhole12** [comment]
I have re-compiled and re-uploaded the binaries, and using `objdump -d libinnative.so | grep -i %ymm` was able to verify that they have no AVX instructions whatsoever in them. Please [re-download the binaries](https://github.com/innative-sdk/innative/releases/tag/v0.1.0) and use `sha1sum` to verify the hash. If something is still crashing, it can't possibly be the instructions anymore.

**Comment by jedisct1** [comment]
This is all good now, thanks!

When binaries are replaced, it takes some time for GitHub to catch up (their CDN keeps caching the old version for a while). This is probably why the second binaries I downloaded were still the original version.

All good!
