### ISSUE TITLE
Unexpected global memory access

### ISSUE THREAD

**Issue by abrown** [innative-sdk/innative#18]
@blackhole12, I was doing some benchmarking and I noticed that innative inserted some unexpected instructions:
```
   ...
   27a64:       89 7c 24 0c             mov    %edi,0xc(%rsp)
   27a68:       48 8b 05 f1 55 02 00    mov    0x255f1(%rip),%rax        # 4d060 <benchmark_WASM_memory>
   27a6f:       48 89 44 24 10          mov    %rax,0x10(%rsp)
   27a74:       c7 44 24 08 01 00 00    movl   $0x1,0x8(%rsp)
   ...
```

The WASM fibonacci function I am using shouldn't be using global memory but it does have a `local`:
```
(func $fibonacci (type 5) (param i32) (result i32)
    (local i32)
    i32.const 1
    local.set 1
    ...
```

Why do you think this is happening? Is there some flag I can add to remove this unexpected `MOV` from `benchmark_WASM_memory`?

**Comment by blackhole12** [comment]
inNative has to cache the global memory access for every single function in order to let LLVM properly optimize memory accesses (otherwise, LLVM would reload the global memory pointer for every single memory load or store). It relies on LLVM optimizing out unnecessary memory loads, which in this case appears to not be happening.

It is possible you are calling a function which itself allocates memory, which sets the global memory cache, which is then failing to be optimized out after not being accessed again. However, you haven't posted any webassembly code and no example to reproduce the error, so it's impossible to tell.

**Comment by abrown** [comment]
```
  (func $fib2 (type 5) (param i32) (result i32)
    (local i32)
    i32.const 1
    local.set 1
    block  ;; label = @1
      local.get 0
      i32.const 2
      i32.lt_u
      br_if 0 (;@1;)
      i32.const 1
      local.set 1
      loop  ;; label = @2
        local.get 0
        i32.const -2
        i32.add
        call $fib2
        local.get 1
        i32.add
        local.set 1
        local.get 0
        i32.const -1
        i32.add
        local.tee 0
        i32.const 1
        i32.gt_u
        br_if 0 (;@2;)
      end
    end
    local.get 1)
```
I'm pulling it out of a rather large module; is that enough to reproduce?

**Comment by abrown** [comment]
Sorry, type 5 is as expected: 
```
  (type (;5;) (func (param i32) (result i32)))
```

**Comment by abrown** [comment]
And one other thing that may help: the function calling `fib2` above does have some `store`s and `load`s. But I should still expect LLVM to optimize away the global memory pointer inside `fib2`, right? (Thanks for the explanation above, by the way; I thought something along those lines but it is helpful to get confirmation).

**Comment by blackhole12** [comment]
Just to verify, are you compiling this with -O3 for maximum optimization?

**Comment by abrown** [comment]
Not explicitly: `innative-cmd -f library -o benchmark.so benchmark.wasm`. Should I be?

**Comment by blackhole12** [comment]
While the library tries to turn on optimization automatically, the command line itself can't. Try running `innative-cmd -f library o3 -o benchmark.so benchmark.wasm` instead.

**Comment by abrown** [comment]
Ok, adding the `-f o3` flag does change the x86 and avoids the move from `benchmark_WASM_memory`; I think we can consider this issue closed. I would suggest that flag becomes a default in the future, though, since I wasn't expecting to have to pass it. Thanks!
