### ISSUE TITLE
AddWhiteList fails with empty module name

### ISSUE THREAD

**Issue by smatcher** [innative-sdk/innative#21]
Hi,

While trying to use one of the helper functions I noticed what looks like a bug in innative-cmd (this actually applies to innative in general but I read the innative-cmd code for reference).

If you supply a an argument in the form
`-w my_custom_function`
the argument parser notices that there is no ':' separator and calls AddWhitelist with nullptr for the module_name argument

in main.cpp:442
```
    if(!second)
      (*exports.AddWhitelist)(env, nullptr, first);
    else
      (*exports.AddWhitelist)(env, first, second);
```
however AddWhitelist raises an error when we do this

in tools.cpp:160
```
enum IN_ERROR innative::AddWhitelist(Environment* env, const char* module_name, const char* export_name)
{
  if(!module_name || !export_name)
    return ERR_PARSE_INVALID_NAME;
```

This means that it is impossible to use the innative helper functions unless we specify an environment module name.

**Comment by blackhole12** [comment]
This is a silly error - the `!module_name` check shouldn't have been there. This has been fixed in the master branch.

**Comment by smatcher** [comment]
Thanks for the fix 👍
