### ISSUE TITLE
Support AssemblyScript imports

### ISSUE THREAD

**Issue by jtenner** [innative-sdk/innative#26]
I'm proposing adding two function imports for AssemblyScript that work sort-of like wasi does. The Javascript implementations of these functions exist in the assemblyscript loader located here:

https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L70

The functions are very straight forward and simply write to stdout.

In order to get a string out of an AssemblyScript module, assemblyscript passes up a pointer that points directly at the start of a utf16le string.

The only way to figure out how to determine the size of the string is to inspect the rtSize property of the header block that exists directly before the pointer. The formula is `rtSize >>> 1` because rtSize is a byte length not a string length. The header block definition is shaped like the following struct/class:

https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/rt/common.ts#L36

This file explains the header of each AssemblyScript block which is 16 bytes (32 bit wasm) or (20 bytes in 64 bit wasm) in offset directly before the pointer.

Please ask any questions, because I'm sure I forgot lots of details and this would help assemblyscript devs get started a lot easier.

**Comment by blackhole12** [comment]
This would have to be added when WASI is added as an environment embedding that follows the interface proposal.

**Comment by blackhole12** [comment]
I started peeking at the [interface proposal](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md), and I'm wondering if this would be better to implement as an _interface_, or if they are simplistic enough that a minimal C implementation (like `innative-env`) would be more useful?

**Comment by jtenner** [comment]
They are very simple. Yes. I'll message you on discord later about it.

**Comment by jtenner** [comment]
I will have to try this out!
