### ISSUE TITLE
compile a wasm file compiled by assemblyscript

### ISSUE THREAD

**Issue by zs33** [innative-sdk/innative#51]
Hi, Can I compile a wasm file  compiled by assemblyscript not from c++,  when i executed innative xx.wasm, it said ERR_FATAL_INVALID_MODULE, why? thanks

**Comment by Xe** [comment]
Can you upload the assembly script source and the resulting wasm file?

**Comment by ErikMcClure** [comment]
Be aware that proper assemblyscript support is currently being worked on. We need to support both #26 and potentially #20, which may be the issue you are running into, if the module does not specify a standard start function.

**Comment by zs33** [comment]
> Can you upload the assembly script source and the resulting wasm file?
This is the wasm file
https://github.com/jtiscione/webassembly-wave/tree/master/as/build

**Comment by ErikMcClure** [comment]
```  
(export "init" (func $assembly/index/init))
```

This is the problem. Assemblyscript is apparently creating it's own "init" function that does not adhere to any actual webassembly standard. inNative cannot support arbitrary start functions - this particular one takes a completely custom set of arguments that do not make sense outside of assemblyscript. This would require, at minimum, an assemblyscript environment that itself knows how to pass the correct arguments to this function - whatever they are.

Alternatively, you can compile a DLL instead of an EXE and call this function yourself. Simply use `-f library`.

**Comment by zs33** [comment]
how can i compile DLL, is there any guide?   And i'm also confuse how to use the assemblyscript.c you given? thanks

**Comment by ErikMcClure** [comment]
Please read the [Wiki](https://github.com/innative-sdk/innative/wiki) for detailed instructions. The assemblyscript library would be used like this:

```
err = (*exports.AddEmbedding)(env, 0, (void*)"innative-assemblyscript.lib", 0);
```

Check the [Quick Start Guide](https://github.com/innative-sdk/innative/wiki/Quick-Start-Guide) for a quick overview of how to compile and load a DLL.

**Comment by MaxGraey** [comment]
> Assemblyscript is apparently creating it's own "init" function that does not adhere to any actual webassembly standard

Assemblyscript use Binaryen for wasm codegen (same as emscripten) btw. All by wasm spec. `init` function just typical exported function by user same as `step`. If `start` function is empty binaryen just optimize it away

**Comment by ErikMcClure** [comment]
The assemblyscript is assuming there is an entry function with arguments, but because you can't set that as the "start" function in the webassembly module, it's set to "empty" and you must manually invoke whatever init function in order to run the program. "init" may be a common entry point, but it is not a standard one, and thus a runtime like inNative cannot possibly know it exists, which means it cannot compile an EXE.

Whether or not this is "Standard" is up for debate, but this is a problem that keeps coming up over and over again - people try to build a program with a standard main function, then complain because it is impossible for a runtime like this to actually run the program.

**Comment by MaxGraey** [comment]
> "init" may be a common entry point

No, it's just some exported function by user which manually called on host.

**Comment by ErikMcClure** [comment]
At this point it might be worth making a library the default behavior if nothing actually compiles things that are executables.

**Comment by MaxGraey** [comment]
What if follow this rules?
-  If WebAssembly module has start section name or exported `_start` (this standard main used by WASI) - produce executable
- if WebAssembly module hast't start section name or `_start` - produce dynamic library

**Comment by ErikMcClure** [comment]
I will likely have to do this, yes. I was trying to make everything explicit, but if this is a common situation I have no choice but to simply default to a library if no start function is found. This change will go in the next release.

**Comment by zs33** [comment]
> Please read the [Wiki](https://github.com/innative-sdk/innative/wiki) for detailed instructions. The assemblyscript library would be used like this:
> 
> ```
> err = (*exports.AddEmbedding)(env, 0, (void*)"innative-assemblyscript.lib", 0);
> ```
> 
> Check the [Quick Start Guide](https://github.com/innative-sdk/innative/wiki/Quick-Start-Guide) for a quick overview of how to compile and load a DLL.

Thanks for you reply,  i have read (https://github.com/innative-sdk/innative/wiki/Quick-Start-Guide), but i still not very clear how to build the dll, it said  "Simply place this library files somewhere in your project" But my wasm file  just use Assemblyscript  to obtain? where these libs to put? how to compile lib i needed? is it mean i should  compile assemblyscript.c file you provided to a lib file using gcc. And then  where the command "err = (*exports.AddEmbedding)(env, 0, (void*)"innative-assemblyscript.lib", 0);" should i add?  The instruction also said a lot commands about set up the environment, but i also don't know where these commands to add?

In addition,  i tried to run wast file in spec\test\core to know more about how innative works, it also has error: no start start function .  how can i to run tests you provided ? is there any standalone webassembly files can be compiled by innative, thanks a lot!

**Comment by ErikMcClure** [comment]
I do not know how to set up a project using only assemblyscript. The provided instructions are for a C program that loads the DLL. If you need to load the DLL using assemblyscript, I cannot provide instructions. You can try to ask in the discord chat, but I don't know of anyone who has actually gotten this to work.

You cannot create standalone assemblyscript binaries from webassembly right now. It is not possible. It might be possible after WASI support is added, but it hasn't been added yet.

The tests are not standalone. There are operating system specific example scripts located in `/scripts/` - you can attempt to run either `test-posix.wat` or `test-win64.wat`.

**Comment by zs33** [comment]
Thanks for your reply. Is it mean Innative only can be used for wasm file compiled from c program？

I have cloned this project, If i want to run innative-sdk/innative/innative-test/ in this project,  what should i do? just make in this directory?

**Comment by ErikMcClure** [comment]
For all practical purposes, inNative currently can only be embedded from inside a C program, yes. It provides a C interface that will allow languages with FFI to call it as well, but no such bindings have been written yet.

Follow the instructions for [building from source](https://github.com/innative-sdk/innative/wiki/Build-From-Source), and `innative-test` will be in the `bin` directory.

**Comment by ErikMcClure** [comment]
This can't be fully addressed because there's no way to build an EXE out of something that takes an arbitrary init function. Custom start functions were added with b69b45a1af7be4a28fd84a8bc0e3d883d69885b0
