### ISSUE TITLE
glibc version error on ubuntu 18.04

### ISSUE THREAD

**Issue by jeffy1009** [innative-sdk/innative#67]
Hello!

Trying to run `innative-cmd` on ubuntu 18.04 gives this error:
```
innative-cmd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by innative-cmd)
innative-cmd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/shin/proj/wasm/innative/innative-posix-runtime-x64/libinnative.so)
innative-cmd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/shin/proj/wasm/innative/innative-posix-runtime-x64/libinnative.so)
```

It seems that there is no easy way to upgrade glibc without breaking other programs and the best option is to upgrade Ubuntu. I've tried `v0.1.0`, but it's the same. Is innative only tested on Ubuntu >= 19.04 ? If so, it would help if the prerequisites are listed somewhere. Has anyone tried it in Ubuntu 18.04?

**Comment by ErikMcClure** [comment]
inNative is built on ubuntu 18.04 on a regular basis and [does in fact compile](https://travis-ci.com/github/innative-sdk/innative/builds/175290026) (although one of the tests is failing). However, it is built with gcc-9, which you may need to install. The readme does mention: `inNative currently requires C++17 to build`, but only lists a minimum Visual Studio version. [https://gcc.gnu.org/projects/cxx-status.html#cxx1z](According to this), the minimum GCC version is likely gcc-8. I will update the readme to include this.

You should be able to install two different versions of glibc side-by-side. As an alternative, I can try to get the Nix packaging working, and then Nix will handle figuring out how to get the correct compiler version.

**Comment by ErikMcClure** [comment]
I've [re-uploaded the prebuilt binaries](https://github.com/innative-sdk/innative/releases/tag/v0.1.9) compiled using gcc-7, but I'm not sure if this is old enough for ubuntu 18.04 - it may be possible to go all the way down to gcc-6 if some source code modifications are made, but I'll have to actually get an 18.04 install working first.

**Comment by jeffy1009** [comment]
The uploaded prebuilt version still gives `./innative-cmd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/shin/proj/wasm/innative/innative-posix-runtime-x64/libinnative.so)` error. 

I didn't try building from source, so I did and confirmed that in works.
However, `cmake >= 3.13` is required since the prior versions do not understand `-S` and `-B` options.
Also I had to build llvm from source since the prebuilt version was compiled with `gcc 9.x` and gives error when compiling `innative-cmd`.

**Comment by ErikMcClure** [comment]
632b9c82e241f16bc37236101bdbc0b592a967e2 reverted the cmake changes so that older cmake versions can be used. The next prebuilt version of inNative will attempt to use holy-build-box to try to resolve issues on linux.

**Comment by ErikMcClure** [comment]
This appears to be impossible because it's impossible to compile LLVM on the old libc holy-build-box uses ([due to this](https://github.com/phusion/holy-build-box/issues/13)), which means this may be unresolvable. Unless a linux guru can some up with a portable compilation, innative will no longer offer any precompiled binaries for linux.

**Comment by ErikMcClure** [comment]
innative now uses cmake to build and no longer offers prebuilt linux binaries.
